### ISSUE TITLE
VCARD related exception because of Query-Size-Error in SQL and cluttered huge LOG

### ISSUE THREAD

**Issue by nineff** [nextcloud/contacts#295]
Hi!

I noticed my Nextcloud is spitting out huge error messages, which noticeably slow down the whole installation (tested by removing the 43MB (with only one user and accumulated in a few weeks) log file). They do contain SQL statements trying to update some VCARDs, but I'm actually not sure what it is they are trying to do.
I currently have 61 contacts stored in my cloud of which 33 had pictures of various sizes and formats uploaded. The app itself seems to function properly, however, just very slow after a while.

### Steps to reproduce
1. Create some contacts with pictures
2. Wait a few days and let the background Cron.php run (this might include sync attempts by my connected apps, see below)
3. Errors pile up in nextcloud.log and installations lows down noticeably

### Expected behaviour
Large files should not be put into the database as huge querys, 

### Actual behaviour
Nextcloud gets slower every day due to repeated logging of huge querys. And whatever they are trying to do doesn't get done due to them failing.

### Server configuration

**Operating system**:
Arch Linux 64bit

**Web server:**
Apache/2.4.27 

**Database:**
MariaDB 10.1.26

**PHP version:**
PHP 7.1.8 

**Nextcloud version:** (see Nextcloud admin page)
12.0.2

**Contacts version:** (see Nextcloud apps page)
1.5.3

**Updated from an older Nextcloud or fresh install:**
Upgraded from Nextcloud 11 which was installed fresh a while ago

**Signing status:**
No errors have been found.

**List of activated apps:**

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - checksum: 0.3.5
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxedit: 0.0.7
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap
```
</details>

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "octn6j02f717",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nineff.de",
            "nikolaineff.de",
            "www.nineff.de",
            "www.nikolaineff.de",
            "78.46.36.135"
        ],
        "datadirectory": "\/usr\/share\/webapps\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/nineff.de\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0.5
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\SVG"
        ],
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
CalDAV Sync using Thunderbird 56.0b3 (32-Bit) / Lightning 58 a1
CardDAV Sync using Thunderbird / SoGo Connector 31.0.2

### Client configuration
**Browser:**
Firefox 56.0b4 (64-Bit)

**Operating system:**
Win 7 SP1 64 bit

**CardDAV-clients:**
[DavDroid](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&referrer=utm_source%3Dhomepage)

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"OOyPyDGJmD8CYQmUKkqw","level":3,"time":"2017-08-21T10:33:50+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Error while running background job (class: OCA\\DAV\\CardDAV\\SyncJob, arguments: ): {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_cards` SET `carddata` = ?, `lastmodified` = ?, `size` = ?, `etag` = ? WHERE (`uri` = ?) AND (`addressbookid` = ?)' with params [\\\"BEGIN:VCARD\\\\r\\\\nVERSION:3.0\\\\r\\\\nPRODID:-\\\\\\\/\\\\\\\/Sabre\\\\\\\/\\\\\\\/Sabre VObject 4.1.2\\\\\\\/\\\\\\\/EN\\\\r\\\\nUID:niko\\\\r\\\\nPHOTO;ENCODING=b;TYPE=image\\\\\\\/jpeg:\\\\\\\/9j\\\\\\\/4AAQSkZJRgABAQEAYABgAAD\\\\\\\/\\\\\\\/gA7Q1JFQVRPUj\\\\r\\\\n 

....   //very long heavyly escaped base64 encoded sequence here

x\\\\\\\/u1sopmiZno\\\\\\\/wC8xsXzP71VyJE2ITIN3VqLByn\\\\\\\/2Q==\\\\r\\\\nFN:niko\\\\r\\\\nN:niko;;;;\\\\r\\\\nEMAIL;TYPE=OTHER:**EMAIL***\\\\r\\\\nCLOUD:**EMAIL**\\\\\\\/nextcloud\\\\r\\\\nEND:VCARD\\\\r\\\\n\\\", 1503311630, 2574488, \\\"57a4b02965dda0065647740ef7a3ffc1\\\", \\\"Database:niko.vcf\\\", \\\"2\\\"]:\\n\\nSQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_card...', Array)\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(213): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `oc_card...', Array, Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `oc_card...', Array, Array)\\n#4 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(213): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CardDAV\\\/CardDavBackend.php(663): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CardDAV\\\/SyncService.php(284): OCA\\\\DAV\\\\CardDAV\\\\CardDavBackend->updateCard('2', 'Database:niko.v...', 'BEGIN:VCARD\\\\r\\\\nVE...')\\n#7 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CardDAV\\\/SyncService.php(320): OCA\\\\DAV\\\\CardDAV\\\\SyncService->updateUser(Object(OC\\\\User\\\\User))\\n#8 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Manager.php(416): OCA\\\\DAV\\\\CardDAV\\\\SyncService->OCA\\\\DAV\\\\CardDAV\\\\{closure}(Object(OC\\\\User\\\\User))\\n#9 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CardDAV\\\/SyncService.php(324): OC\\\\User\\\\Manager->callForAllUsers(Object(Closure))\\n#10 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CardDAV\\\/SyncJob.php(40): OCA\\\\DAV\\\\CardDAV\\\\SyncService->syncInstance()\\n#11 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(59): OCA\\\\DAV\\\\CardDAV\\\\SyncJob->run(NULL)\\n#12 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(54): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#13 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/cron.php(124): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#14 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","userAgent":"--","version":"12.0.2.0"}
{"reqId":"OOyPyDGJmD8CYQmUKkqw","level":3,"time":"2017-08-21T10:33:50+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Error while sending QUERY packet. PID=15270 at \/usr\/share\/webapps\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","userAgent":"--","version":"12.0.2.0"}
{"reqId":"OOyPyDGJmD8CYQmUKkqw","level":4,"time":"2017-08-21T10:33:50+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"An exception occurred while executing 'UPDATE `oc_jobs` SET `reserved_at` = '0' WHERE `id` = ?' with params [\"14\"]:\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away","userAgent":"--","version":"12.0.2.0"}

```

**Comment by skjnldsv** [comment]
This isn't related to the contacts app. Please increase the max_allowed_packet settings on your mysql installation :)
