### ISSUE TITLE
Update: Contacts and Groups not showing in one user account after update to 11.0.0 (Contacts 1.5.2)

### ISSUE THREAD

**Issue by eggithub** [nextcloud/contacts#58]
UPDATE: Not that same as #53 -> this issue refers  to Contacts 1.5.2

### Steps to reproduce
1. login with user that has the "not showing contact" issue
2. click contacts
3. list of people does not load (spinning circle
4. none of the other user on my server has issues

### Expected behaviour
List of people should show

### Actual behaviour
list of people not showing, hour glass

### Server configuration
**Operating system**:
Linux ... 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Web server:**
Server version: Apache/2.4.23 (Debian)
Server built:   2016-11-19T23:33:13

**Database:**
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.6.27-0+deb8u1 (cli) (built: Oct 15 2016 15:53:28)

**Nextcloud version:** (see Nextcloud admin page)
11.0.0

**Contacts version:** (see Nextcloud apps page)
1.5.2

**Updated from an older Nextcloud or fresh install:**
Updated from 10.0.2

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - activity: 2.4.1
  - bookmarks: 0.9.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - user_external
  - user_ldap
  - user_saml
```

**The content of config/config.php:**
```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 3,
        "logtimezone": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "",
        "maintenance": false,
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "theme": "",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
        ],
        "forcessl": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF"
        ],
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "appstore.experimental.enabled": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
firefox 50.0.x

**Operating system:**
Win7

**CardDAV-clients:**
N/A

#### Web server error log
```
Fatal	webdav	Sabre\VObject\ParseException: Unsupported CHARSET: utf-8

    /var/www/nextcloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 234: Sabre\VObject\Parser\MimeDir->readProperty('X-MS-OL-DESIGN;...')
    /var/www/nextcloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 181: Sabre\VObject\Parser\MimeDir->parseLine('X-MS-OL-DESIGN;...')
    /var/www/nextcloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 89: Sabre\VObject\Parser\MimeDir->parseDocument()
    /var/www/nextcloud/3rdparty/sabre/vobject/lib/Reader.php - line 46: Sabre\VObject\Parser\MimeDir->parse('BEGIN VCARD\r\nVE...', 0)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php - line 855: Sabre\VObject\Reader read('BEGIN VCARD\r\nVE...')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php - line 494: Sabre\CardDAV\Plugin->convertVCard('BEGIN VCARD\r\nVE...', 'vcard3')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php - line 203: Sabre\CardDAV\Plugin->addressbookQueryReport(Object(Sabre\CardDAV\Xml\Request\AddressBookQueryReport))
    [internal function] Sabre\CardDAV\Plugin->report('{urn ietf param...', Object(Sabre\CardDAV\Xml\Request\AddressBookQueryReport), 'addressbooks/us...')
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 718: Sabre\Event\EventEmitter->emit('report', Array)
    [internal function] Sabre\DAV\CorePlugin->httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method REPORT', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"8Akay+nHCkBr\/RFl4Rj5","remoteAddr":"***REMOVED SENSITIVE VALUE***","app":"webdav","message":"Exception: {\"Message\":\"Unsupported CHARSET: utf-8\",\"Exception\":\"Sabre\\\\VObject\\\\ParseException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(234): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty('X-MS-OL-DESIGN;...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(181): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('X-MS-OL-DESIGN;...')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(89): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(46): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCARD\\\\r\\\\nVE...', 0)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(855): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCARD\\\\r\\\\nVE...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(494): Sabre\\\\CardDAV\\\\Plugin->convertVCard('BEGIN:VCARD\\\\r\\\\nVE...', 'vcard3')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(203): Sabre\\\\CardDAV\\\\Plugin->addressbookQueryReport(Object(Sabre\\\\CardDAV\\\\Xml\\\\Request\\\\AddressBookQueryReport))\\n#7 [internal function]: Sabre\\\\CardDAV\\\\Plugin->report('{urn:ietf:param...', Object(Sabre\\\\CardDAV\\\\Xml\\\\Request\\\\AddressBookQueryReport), 'addressbooks\\\/us...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(718): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#16 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":477,\"User\":\""***REMOVED SENSITIVE VALUE***"\"}","level":4,"time":"2016-12-13T17:36:57+01:00","method":"REPORT","url":"\/nextcloud\/remote.php\/dav\/addressbooks\/users\/"***REMOVED SENSITIVE VALUE***"\/contacts\/","user":"***REMOVED SENSITIVE VALUE***","version":"11.0.0.10"}

```

#### Browser log
```
N/A
```

**Comment by eggithub** [comment]
It might have something to do with .vcf contact imports from Outlook 2010. Example below with sensitive data removed. Logs clearly talk about charsets... NC10.0.x also did not support VCARD 2.1 anymore I believe?

```
BEGIN:VCARD
VERSION:2.1
N;LANGUAGE=en-us:"***REMOVED SENSITIVE VALUE***";"***REMOVED SENSITIVE VALUE***"
FN:"***REMOVED SENSITIVE VALUE***"
ORG:;"***REMOVED SENSITIVE VALUE***"
TEL;WORK;VOICE:"***REMOVED SENSITIVE VALUE***"
TEL;CELL;VOICE:"***REMOVED SENSITIVE VALUE***"
ADR;WORK;PREF:;"***REMOVED SENSITIVE VALUE***";"***REMOVED SENSITIVE VALUE***";"***REMOVED SENSITIVE VALUE***";;"***REMOVED SENSITIVE VALUE***";"***REMOVED SENSITIVE VALUE***"
LABEL;WORK;PREF;ENCODING=QUOTED-PRINTABLE:"***REMOVED SENSITIVE VALUE***"=0D=0A=
"***REMOVED SENSITIVE VALUE***"=0D=0A=
"***REMOVED SENSITIVE VALUE***"
X-MS-OL-DEFAULT-POSTAL-ADDRESS:2
EMAIL;PREF;INTERNET:"***REMOVED SENSITIVE VALUE***"
PHOTO;TYPE=JPEG;ENCODING=BASE64:
 "***REMOVED SENSITIVE VALUE***"

X-MS-OL-DESIGN;CHARSET=utf-8:<card xmlns="http://schemas.microsoft.com/office/outlook/12/electronicbusinesscards" ver="1.0" layout="left" bgcolor="ffffff"><img xmlns="" align="tleft" area="32" use="photo"/><fld xmlns="" prop="name" align="left" dir="ltr" style="b" color="000000" size="10"/><fld xmlns="" prop="dept" align="left" dir="ltr" color="000000" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="telwork" align="left" dir="ltr" color="000000" size="8"><label align="right" color="626262">Work</label></fld><fld xmlns="" prop="telcell" align="left" dir="ltr" color="000000" size="8"><label align="right" color="626262">Mobile</label></fld><fld xmlns="" prop="email" align="left" dir="ltr" color="000000" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="addrwork" align="left" dir="ltr" color="000000" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" size="8"/></card>
X-MS-MANAGER:"***REMOVED SENSITIVE VALUE***"
REV:20161028T130502Z
END:VCARD
```

**Comment by skjnldsv** [comment]
Duplicate #53 ?

**Comment by eggithub** [comment]
I don't know. The contact app version is not the same 1.5.1 vs 1.5.2. The problem looks the same but that can be deceiving.

I was wondering if perhaps the VCF Contact card xml code within the vcard is possibly causing this issue. I say this because the log file refers to a UTF-8 error. UTF-8 is used as charset in this Card markup code.

Tell me if you need more info from my server or perhaps clients...

Cheers!

**Comment by eggithub** [comment]
This is what I see btw for this specific user:

![2016-12-15 12 04 30](https://cloud.githubusercontent.com/assets/5030914/21221784/0bd2aada-c2bf-11e6-905e-c93ffd67b920.png)

No contacts, no groups...

**Comment by TonyBostonTB** [comment]
This happens to me too but with other specs listed below:
OS: FreeBSD 11
PHP 7.0.14
Database: PostgreSQL 9.5.5

It used to work with NC9 + NC10

**Comment by iGormilhit** [comment]
I'm encoutering the same behaviour, upgraded from nextcloud 10.0.1 to 11.0, using contacts 1.5.2, Debian 3.16.36-1+deb8u2, mysql  Ver 15.1 Distrib 10.0.28-MariaDB.
It's the first time I have this kind of problem after an upgrade.
No sync connector seems to be able to connect (Davdroid, Sogo Connector). Davdroid is having a 404 response when trying to connect.

**Comment by Akhenaton** [comment]
I encountered a problem in NC 11.0 that i had not in 10.0 with one contact. I've solved it simply by erasing this contact and recreating it. (Something to do with the contact image). If you use the nice Davdroid app, try to sync and in case of error(s) you can browse a nice and detailed debugging log. I was able to see immediately in this Davdroid log the culprit.

**Comment by eggithub** [comment]
I solved the issue by:

- backup contacts of my phone
- removing all contacts from my phone -> triggers a sync and removes contacts from nextcloud
- imported the backup on my phone -> this did not trigger the same issue in the nextcloud contacts app

I was unable however, to import the backup in the nextcloud contacts app...

so this works... but is off course not the prefered way.

**Comment by ZorgeR** [comment]
Same issue here, forever spinning whell after upgrade contacts app and nexcloud.
Also in browser console:
angular.isBoolean is not a function in apps/contacts/js/public/script.js

**Comment by skjnldsv** [comment]
Duplicate #53
